# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_0_0/design_1_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_0_0 || ORIG_REF_NAME==design_1_adpt_in_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_0_0/design_1_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_0_0 || ORIG_REF_NAME==design_1_adpt_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ram_dp1_256x8_0_0/design_1_ram_dp1_256x8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ram_dp1_256x8_0_0 || ORIG_REF_NAME==design_1_ram_dp1_256x8_0_0} -quiet] -quiet

# IP: ip/ram1/ram1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram1 || ORIG_REF_NAME==ram1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ram_dp1_256x8_1_0/design_1_ram_dp1_256x8_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ram_dp1_256x8_1_0 || ORIG_REF_NAME==design_1_ram_dp1_256x8_1_0} -quiet] -quiet

# IP: ip/ram1/ram1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram1 || ORIG_REF_NAME==ram1} -quiet] -quiet

# XDC: d:/coding_hong/lab10/lab10.gen/sources_1/bd/design_1/design_1_ooc.xdc
