# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivadoRepo/lab9/lab9.srcs/sources_1/bd/design_1/ip/design_1_rom0_64x24_0_0/design_1_rom0_64x24_0_0.xci
# IP: The module: 'design_1_rom0_64x24_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/vivadoRepo/lab9/lab9.srcs/sources_1/ip/rom0/rom0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom0 || ORIG_REF_NAME==rom0} -quiet] -quiet

# IP: d:/vivadoRepo/lab9/lab9.srcs/sources_1/bd/design_1/ip/design_1_rom0_64x24_0_0/design_1_rom0_64x24_0_0.xci
# IP: The module: 'design_1_rom0_64x24_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/vivadoRepo/lab9/lab9.srcs/sources_1/ip/rom0/rom0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom0 || ORIG_REF_NAME==rom0} -quiet] -quiet
