# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_0_0/design_1_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_0_0 || ORIG_REF_NAME==design_1_adpt_in_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_0_0/design_1_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_0_0 || ORIG_REF_NAME==design_1_adpt_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cla8_0_0/design_1_cla8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cla8_0_0 || ORIG_REF_NAME==design_1_cla8_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mod8_control_0_0/design_1_mod8_control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mod8_control_0_0 || ORIG_REF_NAME==design_1_mod8_control_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pack8_0_0/design_1_pack8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pack8_0_0 || ORIG_REF_NAME==design_1_pack8_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pack8_1_0/design_1_pack8_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pack8_1_0 || ORIG_REF_NAME==design_1_pack8_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_unpack8_0_0/design_1_unpack8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_unpack8_0_0 || ORIG_REF_NAME==design_1_unpack8_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and1_0_0/design_1_and1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and1_0_0 || ORIG_REF_NAME==design_1_and1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and1_1_0/design_1_and1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and1_1_0 || ORIG_REF_NAME==design_1_and1_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and1_2_0/design_1_and1_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and1_2_0 || ORIG_REF_NAME==design_1_and1_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and1_3_0/design_1_and1_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and1_3_0 || ORIG_REF_NAME==design_1_and1_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and1_4_0/design_1_and1_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and1_4_0 || ORIG_REF_NAME==design_1_and1_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and1_5_0/design_1_and1_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and1_5_0 || ORIG_REF_NAME==design_1_and1_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and1_6_0/design_1_and1_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and1_6_0 || ORIG_REF_NAME==design_1_and1_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and1_7_0/design_1_and1_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and1_7_0 || ORIG_REF_NAME==design_1_and1_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m74161_0_0/design_1_m74161_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m74161_0_0 || ORIG_REF_NAME==design_1_m74161_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_2_0/design_1_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_2_0 || ORIG_REF_NAME==design_1_xlconstant_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_3_0/design_1_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_3_0 || ORIG_REF_NAME==design_1_xlconstant_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m74194_0_0/design_1_m74194_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m74194_0_0 || ORIG_REF_NAME==design_1_m74194_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m74194_modified_0_0/design_1_m74194_modified_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m74194_modified_0_0 || ORIG_REF_NAME==design_1_m74194_modified_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xor1_0_0/design_1_xor1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xor1_0_0 || ORIG_REF_NAME==design_1_xor1_0_0} -quiet] -quiet

# XDC: f:/Haoyang_Sun/experiments/labs/exp1/exp1.gen/sources_1/bd/design_1/design_1_ooc.xdc
