# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_0_0/design_1_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_0_0 || ORIG_REF_NAME==design_1_adpt_in_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_3_4/design_1_FA_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_3_4 || ORIG_REF_NAME==design_1_FA_3_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_2_4/design_1_FA_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_2_4 || ORIG_REF_NAME==design_1_FA_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_1_4/design_1_FA_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_1_4 || ORIG_REF_NAME==design_1_FA_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_4/design_1_FA_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_4 || ORIG_REF_NAME==design_1_FA_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_3_3/design_1_FA_3_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_3_3 || ORIG_REF_NAME==design_1_FA_3_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_2_3/design_1_FA_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_2_3 || ORIG_REF_NAME==design_1_FA_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_1_3/design_1_FA_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_1_3 || ORIG_REF_NAME==design_1_FA_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_3/design_1_FA_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_3 || ORIG_REF_NAME==design_1_FA_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_3_2/design_1_FA_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_3_2 || ORIG_REF_NAME==design_1_FA_3_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_2_2/design_1_FA_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_2_2 || ORIG_REF_NAME==design_1_FA_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_1_2/design_1_FA_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_1_2 || ORIG_REF_NAME==design_1_FA_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_2/design_1_FA_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_2 || ORIG_REF_NAME==design_1_FA_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_3_0/design_1_FA_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_3_0 || ORIG_REF_NAME==design_1_FA_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_2_0/design_1_FA_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_2_0 || ORIG_REF_NAME==design_1_FA_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_1_0/design_1_FA_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_1_0 || ORIG_REF_NAME==design_1_FA_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_0/design_1_FA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_0 || ORIG_REF_NAME==design_1_FA_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_15_0/design_1_and2_15_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_15_0 || ORIG_REF_NAME==design_1_and2_15_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_14_0/design_1_and2_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_14_0 || ORIG_REF_NAME==design_1_and2_14_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_13_0/design_1_and2_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_13_0 || ORIG_REF_NAME==design_1_and2_13_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_12_0/design_1_and2_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_12_0 || ORIG_REF_NAME==design_1_and2_12_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_11_0/design_1_and2_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_11_0 || ORIG_REF_NAME==design_1_and2_11_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_10_0/design_1_and2_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_10_0 || ORIG_REF_NAME==design_1_and2_10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_9_0/design_1_and2_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_9_0 || ORIG_REF_NAME==design_1_and2_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_8_0/design_1_and2_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_8_0 || ORIG_REF_NAME==design_1_and2_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_7_0/design_1_and2_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_7_0 || ORIG_REF_NAME==design_1_and2_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_6_0/design_1_and2_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_6_0 || ORIG_REF_NAME==design_1_and2_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_5_0/design_1_and2_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_5_0 || ORIG_REF_NAME==design_1_and2_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_4_0/design_1_and2_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_4_0 || ORIG_REF_NAME==design_1_and2_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_3_0/design_1_and2_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_3_0 || ORIG_REF_NAME==design_1_and2_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_2_0/design_1_and2_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_2_0 || ORIG_REF_NAME==design_1_and2_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_1_0/design_1_and2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_1_0 || ORIG_REF_NAME==design_1_and2_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_0_0/design_1_and2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_0_0 || ORIG_REF_NAME==design_1_and2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_15_4/design_1_FA_15_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_15_4 || ORIG_REF_NAME==design_1_FA_15_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_14_4/design_1_FA_14_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_14_4 || ORIG_REF_NAME==design_1_FA_14_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_13_4/design_1_FA_13_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_13_4 || ORIG_REF_NAME==design_1_FA_13_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_12_4/design_1_FA_12_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_12_4 || ORIG_REF_NAME==design_1_FA_12_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_11_4/design_1_FA_11_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_11_4 || ORIG_REF_NAME==design_1_FA_11_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_10_4/design_1_FA_10_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_10_4 || ORIG_REF_NAME==design_1_FA_10_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_9_4/design_1_FA_9_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_9_4 || ORIG_REF_NAME==design_1_FA_9_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_8_4/design_1_FA_8_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_8_4 || ORIG_REF_NAME==design_1_FA_8_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_7_4/design_1_FA_7_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_7_4 || ORIG_REF_NAME==design_1_FA_7_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_6_4/design_1_FA_6_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_6_4 || ORIG_REF_NAME==design_1_FA_6_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_5_4/design_1_FA_5_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_5_4 || ORIG_REF_NAME==design_1_FA_5_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_4_4/design_1_FA_4_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_4_4 || ORIG_REF_NAME==design_1_FA_4_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_3_9/design_1_FA_3_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_3_9 || ORIG_REF_NAME==design_1_FA_3_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_2_9/design_1_FA_2_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_2_9 || ORIG_REF_NAME==design_1_FA_2_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_1_9/design_1_FA_1_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_1_9 || ORIG_REF_NAME==design_1_FA_1_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_9/design_1_FA_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_9 || ORIG_REF_NAME==design_1_FA_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_15_5/design_1_and2_15_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_15_5 || ORIG_REF_NAME==design_1_and2_15_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_14_5/design_1_and2_14_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_14_5 || ORIG_REF_NAME==design_1_and2_14_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_13_5/design_1_and2_13_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_13_5 || ORIG_REF_NAME==design_1_and2_13_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_12_5/design_1_and2_12_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_12_5 || ORIG_REF_NAME==design_1_and2_12_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_11_5/design_1_and2_11_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_11_5 || ORIG_REF_NAME==design_1_and2_11_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_10_5/design_1_and2_10_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_10_5 || ORIG_REF_NAME==design_1_and2_10_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_9_5/design_1_and2_9_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_9_5 || ORIG_REF_NAME==design_1_and2_9_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_8_5/design_1_and2_8_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_8_5 || ORIG_REF_NAME==design_1_and2_8_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_7_5/design_1_and2_7_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_7_5 || ORIG_REF_NAME==design_1_and2_7_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_6_5/design_1_and2_6_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_6_5 || ORIG_REF_NAME==design_1_and2_6_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_5_5/design_1_and2_5_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_5_5 || ORIG_REF_NAME==design_1_and2_5_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_4_5/design_1_and2_4_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_4_5 || ORIG_REF_NAME==design_1_and2_4_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_3_5/design_1_and2_3_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_3_5 || ORIG_REF_NAME==design_1_and2_3_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_2_5/design_1_and2_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_2_5 || ORIG_REF_NAME==design_1_and2_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_1_5/design_1_and2_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_1_5 || ORIG_REF_NAME==design_1_and2_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_0_5/design_1_and2_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_0_5 || ORIG_REF_NAME==design_1_and2_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_15_5/design_1_FA_15_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_15_5 || ORIG_REF_NAME==design_1_FA_15_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_14_5/design_1_FA_14_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_14_5 || ORIG_REF_NAME==design_1_FA_14_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_13_5/design_1_FA_13_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_13_5 || ORIG_REF_NAME==design_1_FA_13_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_12_5/design_1_FA_12_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_12_5 || ORIG_REF_NAME==design_1_FA_12_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_11_5/design_1_FA_11_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_11_5 || ORIG_REF_NAME==design_1_FA_11_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_10_5/design_1_FA_10_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_10_5 || ORIG_REF_NAME==design_1_FA_10_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_9_5/design_1_FA_9_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_9_5 || ORIG_REF_NAME==design_1_FA_9_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_8_5/design_1_FA_8_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_8_5 || ORIG_REF_NAME==design_1_FA_8_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_7_5/design_1_FA_7_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_7_5 || ORIG_REF_NAME==design_1_FA_7_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_6_5/design_1_FA_6_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_6_5 || ORIG_REF_NAME==design_1_FA_6_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_5_5/design_1_FA_5_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_5_5 || ORIG_REF_NAME==design_1_FA_5_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_4_5/design_1_FA_4_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_4_5 || ORIG_REF_NAME==design_1_FA_4_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_3_10/design_1_FA_3_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_3_10 || ORIG_REF_NAME==design_1_FA_3_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_2_10/design_1_FA_2_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_2_10 || ORIG_REF_NAME==design_1_FA_2_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_1_10/design_1_FA_1_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_1_10 || ORIG_REF_NAME==design_1_FA_1_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_10/design_1_FA_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_10 || ORIG_REF_NAME==design_1_FA_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_15_6/design_1_and2_15_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_15_6 || ORIG_REF_NAME==design_1_and2_15_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_14_6/design_1_and2_14_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_14_6 || ORIG_REF_NAME==design_1_and2_14_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_13_6/design_1_and2_13_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_13_6 || ORIG_REF_NAME==design_1_and2_13_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_12_6/design_1_and2_12_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_12_6 || ORIG_REF_NAME==design_1_and2_12_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_11_6/design_1_and2_11_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_11_6 || ORIG_REF_NAME==design_1_and2_11_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_10_6/design_1_and2_10_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_10_6 || ORIG_REF_NAME==design_1_and2_10_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_9_6/design_1_and2_9_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_9_6 || ORIG_REF_NAME==design_1_and2_9_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_8_6/design_1_and2_8_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_8_6 || ORIG_REF_NAME==design_1_and2_8_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_7_6/design_1_and2_7_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_7_6 || ORIG_REF_NAME==design_1_and2_7_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_6_6/design_1_and2_6_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_6_6 || ORIG_REF_NAME==design_1_and2_6_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_5_6/design_1_and2_5_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_5_6 || ORIG_REF_NAME==design_1_and2_5_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_4_6/design_1_and2_4_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_4_6 || ORIG_REF_NAME==design_1_and2_4_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_3_6/design_1_and2_3_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_3_6 || ORIG_REF_NAME==design_1_and2_3_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_2_6/design_1_and2_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_2_6 || ORIG_REF_NAME==design_1_and2_2_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_1_6/design_1_and2_1_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_1_6 || ORIG_REF_NAME==design_1_and2_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_0_6/design_1_and2_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_0_6 || ORIG_REF_NAME==design_1_and2_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_15_6/design_1_FA_15_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_15_6 || ORIG_REF_NAME==design_1_FA_15_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_14_6/design_1_FA_14_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_14_6 || ORIG_REF_NAME==design_1_FA_14_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_13_6/design_1_FA_13_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_13_6 || ORIG_REF_NAME==design_1_FA_13_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_12_6/design_1_FA_12_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_12_6 || ORIG_REF_NAME==design_1_FA_12_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_11_6/design_1_FA_11_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_11_6 || ORIG_REF_NAME==design_1_FA_11_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_10_6/design_1_FA_10_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_10_6 || ORIG_REF_NAME==design_1_FA_10_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_9_6/design_1_FA_9_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_9_6 || ORIG_REF_NAME==design_1_FA_9_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_8_6/design_1_FA_8_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_8_6 || ORIG_REF_NAME==design_1_FA_8_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_7_6/design_1_FA_7_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_7_6 || ORIG_REF_NAME==design_1_FA_7_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_6_6/design_1_FA_6_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_6_6 || ORIG_REF_NAME==design_1_FA_6_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_5_6/design_1_FA_5_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_5_6 || ORIG_REF_NAME==design_1_FA_5_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_4_6/design_1_FA_4_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_4_6 || ORIG_REF_NAME==design_1_FA_4_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_3_11/design_1_FA_3_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_3_11 || ORIG_REF_NAME==design_1_FA_3_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_2_11/design_1_FA_2_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_2_11 || ORIG_REF_NAME==design_1_FA_2_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_1_11/design_1_FA_1_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_1_11 || ORIG_REF_NAME==design_1_FA_1_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_11/design_1_FA_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_11 || ORIG_REF_NAME==design_1_FA_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_15_7/design_1_and2_15_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_15_7 || ORIG_REF_NAME==design_1_and2_15_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_14_7/design_1_and2_14_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_14_7 || ORIG_REF_NAME==design_1_and2_14_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_13_7/design_1_and2_13_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_13_7 || ORIG_REF_NAME==design_1_and2_13_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_12_7/design_1_and2_12_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_12_7 || ORIG_REF_NAME==design_1_and2_12_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_11_7/design_1_and2_11_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_11_7 || ORIG_REF_NAME==design_1_and2_11_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_10_7/design_1_and2_10_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_10_7 || ORIG_REF_NAME==design_1_and2_10_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_9_7/design_1_and2_9_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_9_7 || ORIG_REF_NAME==design_1_and2_9_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_8_7/design_1_and2_8_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_8_7 || ORIG_REF_NAME==design_1_and2_8_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_7_7/design_1_and2_7_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_7_7 || ORIG_REF_NAME==design_1_and2_7_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_6_7/design_1_and2_6_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_6_7 || ORIG_REF_NAME==design_1_and2_6_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_5_7/design_1_and2_5_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_5_7 || ORIG_REF_NAME==design_1_and2_5_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_4_7/design_1_and2_4_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_4_7 || ORIG_REF_NAME==design_1_and2_4_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_3_7/design_1_and2_3_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_3_7 || ORIG_REF_NAME==design_1_and2_3_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_2_7/design_1_and2_2_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_2_7 || ORIG_REF_NAME==design_1_and2_2_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_1_7/design_1_and2_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_1_7 || ORIG_REF_NAME==design_1_and2_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_0_7/design_1_and2_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_0_7 || ORIG_REF_NAME==design_1_and2_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_12/design_1_FA_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_12 || ORIG_REF_NAME==design_1_FA_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_1/design_1_xlconstant_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_1 || ORIG_REF_NAME==design_1_xlconstant_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_2/design_1_xlconstant_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_2 || ORIG_REF_NAME==design_1_xlconstant_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_3/design_1_xlconstant_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_3 || ORIG_REF_NAME==design_1_xlconstant_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out1_0_0/design_1_adpt_out1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out1_0_0 || ORIG_REF_NAME==design_1_adpt_out1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_13/design_1_FA_0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_13 || ORIG_REF_NAME==design_1_FA_0_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_14/design_1_FA_0_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_14 || ORIG_REF_NAME==design_1_FA_0_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_15/design_1_FA_0_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_15 || ORIG_REF_NAME==design_1_FA_0_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_16/design_1_FA_0_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_16 || ORIG_REF_NAME==design_1_FA_0_16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_1_12/design_1_FA_1_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_1_12 || ORIG_REF_NAME==design_1_FA_1_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_2_12/design_1_FA_2_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_2_12 || ORIG_REF_NAME==design_1_FA_2_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_3_12/design_1_FA_3_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_3_12 || ORIG_REF_NAME==design_1_FA_3_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_18/design_1_FA_0_18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_18 || ORIG_REF_NAME==design_1_FA_0_18} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_1_14/design_1_FA_1_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_1_14 || ORIG_REF_NAME==design_1_FA_1_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_2_14/design_1_FA_2_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_2_14 || ORIG_REF_NAME==design_1_FA_2_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_3_14/design_1_FA_3_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_3_14 || ORIG_REF_NAME==design_1_FA_3_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_4_7/design_1_FA_4_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_4_7 || ORIG_REF_NAME==design_1_FA_4_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_5_7/design_1_FA_5_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_5_7 || ORIG_REF_NAME==design_1_FA_5_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_6_7/design_1_FA_6_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_6_7 || ORIG_REF_NAME==design_1_FA_6_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_7_7/design_1_FA_7_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_7_7 || ORIG_REF_NAME==design_1_FA_7_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_8/design_1_xlconstant_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_8 || ORIG_REF_NAME==design_1_xlconstant_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_20/design_1_FA_0_20.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_20 || ORIG_REF_NAME==design_1_FA_0_20} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_0/design_1_FA1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_0 || ORIG_REF_NAME==design_1_FA1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_1/design_1_FA1_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_1 || ORIG_REF_NAME==design_1_FA1_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_2/design_1_FA1_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_2 || ORIG_REF_NAME==design_1_FA1_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_3/design_1_FA1_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_3 || ORIG_REF_NAME==design_1_FA1_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_4/design_1_FA1_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_4 || ORIG_REF_NAME==design_1_FA1_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_5/design_1_FA1_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_5 || ORIG_REF_NAME==design_1_FA1_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_6/design_1_FA1_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_6 || ORIG_REF_NAME==design_1_FA1_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_7/design_1_FA1_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_7 || ORIG_REF_NAME==design_1_FA1_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_8/design_1_FA1_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_8 || ORIG_REF_NAME==design_1_FA1_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_9/design_1_FA1_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_9 || ORIG_REF_NAME==design_1_FA1_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_10/design_1_FA1_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_10 || ORIG_REF_NAME==design_1_FA1_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_11/design_1_FA1_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_11 || ORIG_REF_NAME==design_1_FA1_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_12/design_1_FA1_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_12 || ORIG_REF_NAME==design_1_FA1_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_13/design_1_FA1_0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_13 || ORIG_REF_NAME==design_1_FA1_0_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA1_0_14/design_1_FA1_0_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA1_0_14 || ORIG_REF_NAME==design_1_FA1_0_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_4/design_1_xlconstant_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_4 || ORIG_REF_NAME==design_1_xlconstant_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA_0_21/design_1_FA_0_21.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA_0_21 || ORIG_REF_NAME==design_1_FA_0_21} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_1/design_1_FA2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_1 || ORIG_REF_NAME==design_1_FA2_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_2/design_1_FA2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_2 || ORIG_REF_NAME==design_1_FA2_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_3/design_1_FA2_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_3 || ORIG_REF_NAME==design_1_FA2_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_4/design_1_FA2_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_4 || ORIG_REF_NAME==design_1_FA2_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_5/design_1_FA2_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_5 || ORIG_REF_NAME==design_1_FA2_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_6/design_1_FA2_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_6 || ORIG_REF_NAME==design_1_FA2_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_7/design_1_FA2_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_7 || ORIG_REF_NAME==design_1_FA2_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_8/design_1_FA2_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_8 || ORIG_REF_NAME==design_1_FA2_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_9/design_1_FA2_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_9 || ORIG_REF_NAME==design_1_FA2_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_10/design_1_FA2_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_10 || ORIG_REF_NAME==design_1_FA2_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_11/design_1_FA2_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_11 || ORIG_REF_NAME==design_1_FA2_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_12/design_1_FA2_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_12 || ORIG_REF_NAME==design_1_FA2_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_13/design_1_FA2_0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_13 || ORIG_REF_NAME==design_1_FA2_0_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_14/design_1_FA2_0_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_14 || ORIG_REF_NAME==design_1_FA2_0_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FA2_0_15/design_1_FA2_0_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FA2_0_15 || ORIG_REF_NAME==design_1_FA2_0_15} -quiet] -quiet

# XDC: f:/Haoyang_Sun/experiments/labs/lab8_ex/lab8_ex.gen/sources_1/bd/design_1/design_1_ooc.xdc
