# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Haoyang_Sun/experiments/labs/lab11/lab11.srcs/sources_1/ip/ram1/ram1.xci
# IP: The module: 'ram1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Haoyang_Sun/experiments/labs/lab11/lab11.gen/sources_1/ip/ram1/ram1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/Haoyang_Sun/experiments/labs/lab11/lab11.srcs/sources_1/ip/ram1/ram1.xci
# IP: The module: 'ram1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Haoyang_Sun/experiments/labs/lab11/lab11.gen/sources_1/ip/ram1/ram1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
