# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_0_0/design_1_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_0_0 || ORIG_REF_NAME==design_1_adpt_in_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_0_0/design_1_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_0_0 || ORIG_REF_NAME==design_1_adpt_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not0_0_1/design_1_not0_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not0_0_1 || ORIG_REF_NAME==design_1_not0_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_0_1/design_1_and3_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_0_1 || ORIG_REF_NAME==design_1_and3_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not0_1_1/design_1_not0_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not0_1_1 || ORIG_REF_NAME==design_1_not0_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_1_0/design_1_and3_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_1_0 || ORIG_REF_NAME==design_1_and3_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or4_0_0/design_1_or4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or4_0_0 || ORIG_REF_NAME==design_1_or4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_2_0/design_1_and3_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_2_0 || ORIG_REF_NAME==design_1_and3_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_3_0/design_1_and3_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_3_0 || ORIG_REF_NAME==design_1_and3_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_4_0/design_1_and3_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_4_0 || ORIG_REF_NAME==design_1_and3_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_5_0/design_1_and3_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_5_0 || ORIG_REF_NAME==design_1_and3_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_6_0/design_1_and3_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_6_0 || ORIG_REF_NAME==design_1_and3_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_7_0/design_1_and3_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_7_0 || ORIG_REF_NAME==design_1_and3_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or4_1_0/design_1_or4_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or4_1_0 || ORIG_REF_NAME==design_1_or4_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or4_2_0/design_1_or4_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or4_2_0 || ORIG_REF_NAME==design_1_or4_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_8_0/design_1_and3_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_8_0 || ORIG_REF_NAME==design_1_and3_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_9_0/design_1_and3_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_9_0 || ORIG_REF_NAME==design_1_and3_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_10_0/design_1_and3_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_10_0 || ORIG_REF_NAME==design_1_and3_10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_11_0/design_1_and3_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_11_0 || ORIG_REF_NAME==design_1_and3_11_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_or4_3_0/design_1_or4_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_or4_3_0 || ORIG_REF_NAME==design_1_or4_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_12_0/design_1_and3_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_12_0 || ORIG_REF_NAME==design_1_and3_12_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_13_0/design_1_and3_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_13_0 || ORIG_REF_NAME==design_1_and3_13_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_14_0/design_1_and3_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_14_0 || ORIG_REF_NAME==design_1_and3_14_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and3_15_0/design_1_and3_15_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and3_15_0 || ORIG_REF_NAME==design_1_and3_15_0} -quiet] -quiet

# XDC: d:/vivadoRepo/lab3/lab3.gen/sources_1/bd/design_1/design_1_ooc.xdc
