# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_0_0/design_1_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_0_0 || ORIG_REF_NAME==design_1_adpt_in_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_0_0/design_1_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_0_0 || ORIG_REF_NAME==design_1_adpt_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not0_0_0/design_1_not0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not0_0_0 || ORIG_REF_NAME==design_1_not0_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_0_0/design_1_and4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_0_0 || ORIG_REF_NAME==design_1_and4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not0_2_0/design_1_not0_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not0_2_0 || ORIG_REF_NAME==design_1_not0_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not0_3_0/design_1_not0_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not0_3_0 || ORIG_REF_NAME==design_1_not0_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_1_0/design_1_and4_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_1_0 || ORIG_REF_NAME==design_1_and4_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_2_0/design_1_and4_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_2_0 || ORIG_REF_NAME==design_1_and4_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_3_0/design_1_and4_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_3_0 || ORIG_REF_NAME==design_1_and4_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_4_0/design_1_and4_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_4_0 || ORIG_REF_NAME==design_1_and4_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_5_0/design_1_and4_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_5_0 || ORIG_REF_NAME==design_1_and4_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_6_0/design_1_and4_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_6_0 || ORIG_REF_NAME==design_1_and4_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_7_0/design_1_and4_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_7_0 || ORIG_REF_NAME==design_1_and4_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not0_1_0/design_1_not0_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not0_1_0 || ORIG_REF_NAME==design_1_not0_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_0_1/design_1_and4_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_0_1 || ORIG_REF_NAME==design_1_and4_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_1_1/design_1_and4_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_1_1 || ORIG_REF_NAME==design_1_and4_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_2_1/design_1_and4_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_2_1 || ORIG_REF_NAME==design_1_and4_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_3_1/design_1_and4_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_3_1 || ORIG_REF_NAME==design_1_and4_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_4_1/design_1_and4_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_4_1 || ORIG_REF_NAME==design_1_and4_4_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_5_1/design_1_and4_5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_5_1 || ORIG_REF_NAME==design_1_and4_5_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_6_1/design_1_and4_6_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_6_1 || ORIG_REF_NAME==design_1_and4_6_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and4_7_1/design_1_and4_7_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and4_7_1 || ORIG_REF_NAME==design_1_and4_7_1} -quiet] -quiet

# XDC: d:/vivadoRepo/lab4/lab4.gen/sources_1/bd/design_1/design_1_ooc.xdc
