# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/vivadoRepo/lab9/lab9.srcs/sources_1/ip/ram_dp0/ram_dp0.xci
# IP: The module: 'ram_dp0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivadoRepo/lab9/lab9.gen/sources_1/ip/ram_dp0/ram_dp0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_dp0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/vivadoRepo/lab9/lab9.srcs/sources_1/ip/ram_dp0/ram_dp0.xci
# IP: The module: 'ram_dp0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivadoRepo/lab9/lab9.gen/sources_1/ip/ram_dp0/ram_dp0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_dp0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
