# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Haoyang_Sun/experiments/labs/lab11/lab11.srcs/sources_1/bd/design_1/ip/design_1_ram_dp1_256x8_2_0/design_1_ram_dp1_256x8_2_0.xci
# IP: The module: 'design_1_ram_dp1_256x8_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/Haoyang_Sun/experiments/labs/lab11/lab11.srcs/sources_1/ip/ram1/ram1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram1 || ORIG_REF_NAME==ram1} -quiet] -quiet

# IP: f:/Haoyang_Sun/experiments/labs/lab11/lab11.srcs/sources_1/bd/design_1/ip/design_1_ram_dp1_256x8_2_0/design_1_ram_dp1_256x8_2_0.xci
# IP: The module: 'design_1_ram_dp1_256x8_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/Haoyang_Sun/experiments/labs/lab11/lab11.srcs/sources_1/ip/ram1/ram1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram1 || ORIG_REF_NAME==ram1} -quiet] -quiet
