# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Haoyang_Sun/experiments/labs/lab12/lab12.srcs/sources_1/bd/design_1/ip/design_1_rom1_256x8_0_0/design_1_rom1_256x8_0_0.xci
# IP: The module: 'design_1_rom1_256x8_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/Haoyang_Sun/experiments/labs/lab12/lab12.srcs/sources_1/ip/rom1/rom1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom1 || ORIG_REF_NAME==rom1} -quiet] -quiet

# IP: f:/Haoyang_Sun/experiments/labs/lab12/lab12.srcs/sources_1/bd/design_1/ip/design_1_rom1_256x8_0_0/design_1_rom1_256x8_0_0.xci
# IP: The module: 'design_1_rom1_256x8_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/Haoyang_Sun/experiments/labs/lab12/lab12.srcs/sources_1/ip/rom1/rom1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom1 || ORIG_REF_NAME==rom1} -quiet] -quiet
