# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ICR_0_0/design_1_ICR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ICR_0_0 || ORIG_REF_NAME==design_1_ICR_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ICR_1_0/design_1_ICR_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ICR_1_0 || ORIG_REF_NAME==design_1_ICR_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_addr_adpt_0_0/design_1_addr_adpt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_addr_adpt_0_0 || ORIG_REF_NAME==design_1_addr_adpt_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_0_0/design_1_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_0_0 || ORIG_REF_NAME==design_1_adpt_in_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_0_0/design_1_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_0_0 || ORIG_REF_NAME==design_1_adpt_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m74LS161_0_0/design_1_m74LS161_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m74LS161_0_0 || ORIG_REF_NAME==design_1_m74LS161_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rom1_256x24_0_0/design_1_rom1_256x24_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rom1_256x24_0_0 || ORIG_REF_NAME==design_1_rom1_256x24_0_0} -quiet] -quiet

# IP: ip/rom1/rom1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom1 || ORIG_REF_NAME==rom1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ICR_0_1/design_1_ICR_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ICR_0_1 || ORIG_REF_NAME==design_1_ICR_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ICR_2_0/design_1_ICR_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ICR_2_0 || ORIG_REF_NAME==design_1_ICR_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ICR_3_0/design_1_ICR_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ICR_3_0 || ORIG_REF_NAME==design_1_ICR_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_0_0/design_1_and2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_0_0 || ORIG_REF_NAME==design_1_and2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_unpack16_0_0/design_1_unpack16_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_unpack16_0_0 || ORIG_REF_NAME==design_1_unpack16_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adder8_0_0/design_1_adder8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adder8_0_0 || ORIG_REF_NAME==design_1_adder8_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_1_0/design_1_and2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_1_0 || ORIG_REF_NAME==design_1_and2_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_2_0/design_1_and2_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_2_0 || ORIG_REF_NAME==design_1_and2_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_unpack_ctrl8_0_0/design_1_unpack_ctrl8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_unpack_ctrl8_0_0 || ORIG_REF_NAME==design_1_unpack_ctrl8_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_unpack8_0_0/design_1_unpack8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_unpack8_0_0 || ORIG_REF_NAME==design_1_unpack8_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_unpack8_1_0/design_1_unpack8_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_unpack8_1_0 || ORIG_REF_NAME==design_1_unpack8_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_unpack8_2_0/design_1_unpack8_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_unpack8_2_0 || ORIG_REF_NAME==design_1_unpack8_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_shifter8_0_1/design_1_shifter8_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_shifter8_0_1 || ORIG_REF_NAME==design_1_shifter8_0_1} -quiet] -quiet

# XDC: f:/Haoyang_Sun/experiments/labs/lab14/lab14.gen/sources_1/bd/design_1/design_1_ooc.xdc
