# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ICR_0_0/design_1_ICR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ICR_0_0 || ORIG_REF_NAME==design_1_ICR_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_0_0/design_1_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_0_0 || ORIG_REF_NAME==design_1_adpt_in_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_0_0/design_1_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_0_0 || ORIG_REF_NAME==design_1_adpt_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_0_0/design_1_and2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_0_0 || ORIG_REF_NAME==design_1_and2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_1_0/design_1_and2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_1_0 || ORIG_REF_NAME==design_1_and2_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_2_0/design_1_and2_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_2_0 || ORIG_REF_NAME==design_1_and2_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_3_0/design_1_and2_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_3_0 || ORIG_REF_NAME==design_1_and2_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_4_0/design_1_and2_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_4_0 || ORIG_REF_NAME==design_1_and2_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_5_0/design_1_and2_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_5_0 || ORIG_REF_NAME==design_1_and2_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_6_0/design_1_and2_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_6_0 || ORIG_REF_NAME==design_1_and2_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_7_0/design_1_and2_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_7_0 || ORIG_REF_NAME==design_1_and2_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_8_0/design_1_and2_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_8_0 || ORIG_REF_NAME==design_1_and2_8_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_9_0/design_1_and2_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_9_0 || ORIG_REF_NAME==design_1_and2_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff_0_0/design_1_dff_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff_0_0 || ORIG_REF_NAME==design_1_dff_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff_1_0/design_1_dff_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff_1_0 || ORIG_REF_NAME==design_1_dff_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff_2_0/design_1_dff_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff_2_0 || ORIG_REF_NAME==design_1_dff_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff_3_0/design_1_dff_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff_3_0 || ORIG_REF_NAME==design_1_dff_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff_4_0/design_1_dff_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff_4_0 || ORIG_REF_NAME==design_1_dff_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff_5_0/design_1_dff_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff_5_0 || ORIG_REF_NAME==design_1_dff_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff_6_0/design_1_dff_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff_6_0 || ORIG_REF_NAME==design_1_dff_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff_7_0/design_1_dff_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff_7_0 || ORIG_REF_NAME==design_1_dff_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not1_0_0/design_1_not1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not1_0_0 || ORIG_REF_NAME==design_1_not1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not1_1_0/design_1_not1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not1_1_0 || ORIG_REF_NAME==design_1_not1_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_not1_2_0/design_1_not1_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_not1_2_0 || ORIG_REF_NAME==design_1_not1_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rom1_256x8_0_0/design_1_rom1_256x8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rom1_256x8_0_0 || ORIG_REF_NAME==design_1_rom1_256x8_0_0} -quiet] -quiet

# IP: ip/rom1/rom1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom1 || ORIG_REF_NAME==rom1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_unpack4_0_0/design_1_unpack4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_unpack4_0_0 || ORIG_REF_NAME==design_1_unpack4_0_0} -quiet] -quiet

# XDC: f:/Haoyang_Sun/experiments/labs/lab12/lab12.gen/sources_1/bd/design_1/design_1_ooc.xdc
